apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: premierpredictor-deployment
spec:
  selector:
    matchLabels:
      app: premierpredictor-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: premierpredictor-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: premierpredictor-app
          image: gcr.io/prempred2/premierpredictor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiKey
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiUrl
            - name: API_URL_COMMENTARY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: apiUrlCommentary
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbUrl
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbUser
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dbPassword
            - name: DYNAMO_DB_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dynamoDbAccessKey
            - name: DYNAMODB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dynamoDbEndpoint
            - name: DYNAMO_DB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: dynamoDbSecretKey
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: jwtSecret
            - name: SEND_GRIP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: premierpredictor-secrets
                  key: sendGridApiKey
            - name: JAVA_OPTS
              value: -Xmx125m -Xms125m -Xss256k -XX:+UseCompressedOops -XX:+UseContainerSupport -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "600Mi"
          readinessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 60